### ISSUE TITLE
Skeleton state

### ISSUE THREAD

**Issue by Daan645** [Annevd/the-web-is-for-everyone-interactive-functionality#4]
Probeer een skeleton state toetevoegen aan je carousel

**Comment by Annevd** [comment]
Gedaan door het dezelfde hoogte en breedte te geven als de playlists.

![Image](https://github.com/Annevd/the-web-is-for-everyone-interactive-functionality/assets/144004647/2b74d131-e956-40df-b533-831fe66f8c71)
